# Generated by Django 5.0 on 2023-12-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created',
        ),
    ]
