# Generated by Django 5.0 on 2023-12-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_team_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='destination',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
