# Generated by Django 5.0 on 2023-12-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_destination_team_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='destination',
            new_name='index',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
