# Generated by Django 5.0 on 2023-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_destination_team_index_remove_team_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
